### ISSUE TITLE
babel-plugin is not enough

### ISSUE THREAD

**Issue by shunitoh** [h13i32maru/ice-cap#3]
### After running esdoc in gulp.shell, error occurred

```
$ gulp build.esdoc
...
/Users/shunitoh/git/.../node_modules/ice-cap/out/src/IceCap.js:18
let logger = new _colorLogger2.default('IceCap');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/shunitoh/git/.../node_modules/esdoc/out/src/Publisher/publish.js:20:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
[16:03:07] 'build.esdoc' errored after 388 ms
[16:03:07] Error: Command `esdoc -c ./esdoc.json` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```
### Not a ES5 description is seen

```
$ grep 'class ' ./out/src/IceCap.js | wc -l
1
$ grep 'let ' ./out/src/IceCap.js | wc -l
25
```
### The following is a modified plan of source

```
$ git diff ./package.json
-    "babel-plugin-transform-es2015-modules-commonjs": "6.7.0",
-    "babel-plugin-transform-es2015-destructuring": "6.6.5",
-    "babel-plugin-transform-es2015-parameters": "6.7.0",
-    "babel-plugin-transform-es2015-spread": "6.6.5",
+    "babel-preset-es2015": "^6.6.0",

$ git diff .babelrc
 {
-  "plugins": [
-    "transform-es2015-modules-commonjs",
-    "transform-es2015-destructuring",
-    "transform-es2015-parameters",
-    "transform-es2015-spread"
-  ]
+  "presets": ["es2015"]
 }
```

Please consider

**Comment by shunitoh** [comment]
https://github.com/h13i32maru/ice-cap/commit/d34780fe25bc5e319b960147d1f6e63931f071b3
